#default 공통설정
spring:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: MYSQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false

---
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    url: jdbc:h2:tcp://localhost/~/push
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: H2

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace