
spring:
  application:
    name: push
  profiles:
    active:
      - local
    include:
      - db
    group:
      local: "db-local"
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  shutdown: graceful
  port: 12290

springdoc:
  packages-to-scan: kr.toka.push.web